default['apache']['mpm'] = 'prefork'
default['magento2vm']['app_name'] = 'magento2'
default['magento2vm']['server_name'] = 'magento2.dev'
default['magento2vm']['approot'] = '/vagrant'
default['magento2vm']['db_password'] = ''